# Copyright (c) 2017-present SIGHUP s.r.l All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

---

bases:
  - vendor/katalog/ingress/cert-manager
  - vendor/katalog/monitoring/prometheus-operator
  - vendor/katalog/storage/rook-operator

patchesStrategicMerge:
  - rook-operator-nodeSelector.yml

configMapGenerator:
  # this will slow down the log amount of the CSI components that otherwise is too high
  - name : rook-ceph-operator-config
    namespace: rook-ceph
    behavior: merge
    literals:
    - CSI_LOG_LEVEL=0
